export const languages = [
  { code: 'en', name: 'English', nativeName: 'English' },
  { code: 'ml', name: 'Malayalam', nativeName: 'മലയാളം' },
  { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்' },
  { code: 'te', name: 'Telugu', nativeName: 'తెలుగు' },
  { code: 'kn', name: 'Kannada', nativeName: 'ಕನ್ನಡ' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी' },
  { code: 'gu', name: 'Gujarati', nativeName: 'ગુજરાતી' },
  { code: 'mr', name: 'Marathi', nativeName: 'मराठी' },
  { code: 'bn', name: 'Bengali', nativeName: 'বাংলা' },
  { code: 'pa', name: 'Punjabi', nativeName: 'ਪੰਜਾਬੀ' },
  { code: 'or', name: 'Odia', nativeName: 'ଓଡ଼ିଆ' },
  { code: 'as', name: 'Assamese', nativeName: 'অসমীয়া' },
];

export const translations = {
  en: {
    welcome: "Welcome to SwasthyaID",
    workerPortal: "Worker Portal",
    hospitalPortal: "Hospital Portal",
    governmentPortal: "Government Portal",
    accessRecords: "Access Your Records",
    registerNow: "Register Now",
    login: "Login",
    logout: "Logout",
    home: "Home",
    healthId: "Health ID",
    mobileOtp: "Mobile OTP",
    register: "Register",
    name: "Name",
    mobileNumber: "Mobile Number",
    email: "Email",
    address: "Address",
    dateOfBirth: "Date of Birth",
    aadharNumber: "Aadhar Number",
    medicalRecords: "Medical Records",
    appointments: "Appointments",
    documents: "Documents",
    profile: "Profile",
    download: "Download",
    aiTranslate: "AI Translate",
    doctorName: "Doctor Name",
    diagnosis: "Diagnosis",
    prescription: "Prescription",
    notes: "Notes",
    visitDate: "Visit Date",
    nextAppointment: "Next Appointment",
    suggestedTests: "Suggested Tests",
    testByWorker: "Test by Worker",
    registeredWorkers: "Registered Workers",
    totalRecords: "Total Records",
    healthTracking: "Health Tracking",
    platformBenefits: "Platform Benefits",
    uniqueHealthId: "Unique digital health ID based on your identity",
    centralizedRecords: "Centralized medical records with AI translation",
    easyMobileAccess: "Easy mobile access with OTP login",
    appointmentTracking: "Appointment tracking and health insights",
    enterHealthId: "Enter your Health ID",
    enterMobile: "Enter your mobile number",
    sendOtp: "Send OTP",
    verifyOtp: "Verify OTP",
    back: "Back",
    backToHome: "Back to Home",
    loading: "Loading...",
    searching: "Searching...",
    noRecordsFound: "No records found",
    noAppointmentsFound: "No appointments found",
    scheduled: "Scheduled",
    completed: "Completed",
    cancelled: "Cancelled",
    rescheduled: "Rescheduled",
    purpose: "Purpose",
    status: "Status",
    refreshData: "Refresh Data"
  },
  ml: {
    welcome: "സ്വാസ്ഥ്യ ഐഡിയിലേക്ക് സ്വാഗതം",
    workerPortal: "തൊഴിലാളി പോർട്ടൽ",
    hospitalPortal: "ആശുപത്രി പോർട്ടൽ",
    governmentPortal: "സർക്കാർ പോർട്ടൽ",
    accessRecords: "നിങ്ങളുടെ രേഖകൾ കാണുക",
    registerNow: "ഇപ്പോൾ രജിസ്റ്റർ ചെയ്യുക",
    login: "ലോഗിൻ",
    logout: "ലോഗൗട്ട്",
    home: "ഹോം",
    healthId: "ആരോഗ്യ ഐഡി",
    mobileOtp: "മൊബൈൽ ഒടിപി",
    register: "രജിസ്റ്റർ",
    name: "പേര്",
    mobileNumber: "മൊബൈൽ നമ്പർ",
    email: "ഇമെയിൽ",
    address: "വിലാസം",
    dateOfBirth: "ജന്മദിനം",
    aadharNumber: "ആധാർ നമ്പർ",
    medicalRecords: "മെഡിക്കൽ രേഖകൾ",
    appointments: "അപ്പോയിന്റ്മെന്റുകൾ",
    documents: "ഡോക്യുമെന്റുകൾ",
    profile: "പ്രൊഫൈൽ",
    download: "ഡൗൺലോഡ്",
    aiTranslate: "AI വിവർത്തനം",
    doctorName: "ഡോക്ടറുടെ പേര്",
    diagnosis: "രോഗനിർണ്ണയം",
    prescription: "കുറിപ്പട",
    notes: "കുറിപ്പുകൾ",
    visitDate: "സന്ദർശന തീയതി",
    nextAppointment: "അടുത്ത അപ്പോയിന്റ്മെന്റ്",
    suggestedTests: "നിർദ്ദേശിച്ച പരിശോധനകൾ",
    testByWorker: "തൊഴിലാളിയുടെ പരിശോധന",
    registeredWorkers: "രജിസ്റ്റർ ചെയ്ത തൊഴിലാളികൾ",
    totalRecords: "മൊത്തം രേഖകൾ",
    healthTracking: "ആരോഗ്യ ട്രാക്കിംഗ്",
    platformBenefits: "പ്ലാറ്റ്ഫോം ആനുകൂല്യങ്ങൾ",
    uniqueHealthId: "നിങ്ങളുടെ ഐഡന്റിറ്റി അടിസ്ഥാനമാക്കിയുള്ള അദ്വിതീയ ഡിജിറ്റൽ ആരോഗ്യ ഐഡി",
    centralizedRecords: "AI വിവർത്തനത്തോടുകൂടിയ കേന്ദ്രീകൃത മെഡിക്കൽ രേഖകൾ",
    easyMobileAccess: "OTP ലോഗിൻ ഉപയോഗിച്ച് എളുപ്പമുള്ള മൊബൈൽ ആക്സസ്",
    appointmentTracking: "അപ്പോയിന്റ്മെന്റ് ട്രാക്കിംഗും ആരോഗ്യ ഉൾക്കാഴ്ചകളും",
    enterHealthId: "നിങ്ങളുടെ ആരോഗ്യ ഐഡി നൽകുക",
    enterMobile: "നിങ്ങളുടെ മൊബൈൽ നമ്പർ നൽകുക",
    sendOtp: "OTP അയയ്ക്കുക",
    verifyOtp: "OTP പരിശോധിക്കുക",
    back: "തിരികെ",
    backToHome: "ഹോമിലേക്ക് തിരികെ",
    loading: "ലോഡ് ചെയ്യുന്നു...",
    searching: "തിരയുന്നു...",
    noRecordsFound: "രേഖകൾ കണ്ടെത്തിയില്ല",
    noAppointmentsFound: "അപ്പോയിന്റ്മെന്റുകൾ കണ്ടെത്തിയില്ല",
    scheduled: "ഷെഡ്യൂൾ ചെയ്തു",
    completed: "പൂർത്തിയായി",
    cancelled: "റദ്ദാക്കി",
    rescheduled: "പുനർ ഷെഡ്യൂൾ ചെയ്തു",
    purpose: "ഉദ്ദേശ്യം",
    status: "സ്ഥിതി",
    refreshData: "ഡാറ്റ പുതുക്കുക"
  },
  hi: {
    welcome: "स्वास्थ्य आईडी में आपका स्वागत है",
    workerPortal: "श्रमिक पोर्टल",
    hospitalPortal: "अस्पताल पोर्टल",
    governmentPortal: "सरकारी पोर्टल",
    accessRecords: "अपने रिकॉर्ड देखें",
    registerNow: "अभी रजिस्टर करें",
    login: "लॉगिन",
    logout: "लॉगआउट",
    home: "होम",
    healthId: "स्वास्थ्य आईडी",
    mobileOtp: "मोबाइल ओटीपी",
    register: "रजिस्टर",
    name: "नाम",
    mobileNumber: "मोबाइल नंबर",
    email: "ईमेल",
    address: "पता",
    dateOfBirth: "जन्म तिथि",
    aadharNumber: "आधार नंबर",
    medicalRecords: "मेडिकल रिकॉर्ड",
    appointments: "अपॉइंटमेंट",
    documents: "दस्तावेज",
    profile: "प्रोफाइल",
    download: "डाउनलोड",
    aiTranslate: "AI अनुवाद",
    doctorName: "डॉक्टर का नाम",
    diagnosis: "निदान",
    prescription: "नुस्खा",
    notes: "टिप्पणियां",
    visitDate: "भेंट की तारीख",
    nextAppointment: "अगली अपॉइंटमेंट",
    suggestedTests: "सुझाए गए टेस्ट",
    testByWorker: "श्रमिक द्वारा टेस्ट",
    registeredWorkers: "पंजीकृत श्रमिक",
    totalRecords: "कुल रिकॉर्ड",
    healthTracking: "स्वास्थ्य ट्रैकिंग",
    platformBenefits: "प्लेटफॉर्म लाभ",
    uniqueHealthId: "आपकी पहचान पर आधारित अद्वितीय डिजिटल स्वास्थ्य आईडी",
    centralizedRecords: "AI अनुवाद के साथ केंद्रीकृत मेडिकल रिकॉर्ड",
    easyMobileAccess: "OTP लॉगिन के साथ आसान मोबाइल एक्सेस",
    appointmentTracking: "अपॉइंटमेंट ट्रैकिंग और स्वास्थ्य अंतर्दृष्टि",
    enterHealthId: "अपनी स्वास्थ्य आईडी दर्ज करें",
    enterMobile: "अपना मोबाइल नंबर दर्ज करें",
    sendOtp: "OTP भेजें",
    verifyOtp: "OTP सत्यापित करें",
    back: "वापस",
    backToHome: "होम पर वापस",
    loading: "लोड हो रहा है...",
    searching: "खोज रहे हैं...",
    noRecordsFound: "कोई रिकॉर्ड नहीं मिला",
    noAppointmentsFound: "कोई अपॉइंटमेंट नहीं मिली",
    scheduled: "निर्धारित",
    completed: "पूर्ण",
    cancelled: "रद्द",
    rescheduled: "पुनर्निर्धारित",
    purpose: "उद्देश्य",
    status: "स्थिति",
    refreshData: "डेटा रीफ्रेश करें"
  },
  ta: {
    welcome: "ஸ்வஸ்த்யா ஐடிக்கு வரவேற்கிறோம்",
    workerPortal: "தொழிலாளர் போர்ட்டல்",
    hospitalPortal: "மருத்துவமனை போர்ட்டல்",
    governmentPortal: "அரசு போர்ட்டல்",
    accessRecords: "உங்கள் பதிவுகளை அணுகவும்",
    registerNow: "இப்போது பதிவு செய்யுங்கள்",
    login: "உள்நுழைய",
    logout: "வெளியேறு",
    home: "முகப்பு",
    healthId: "சுகாதார ஐடி",
    mobileOtp: "மொபைல் ஓடிபி",
    register: "பதிவு",
    name: "பெயர்",
    mobileNumber: "மொபைல் எண்",
    email: "மின்னஞ்சல்",
    address: "முகவரி",
    dateOfBirth: "பிறந்த தேதி",
    aadharNumber: "ஆதார் எண்",
    medicalRecords: "மருத்துவ பதிவுகள்",
    appointments: "சந்திப்புகள்",
    documents: "ஆவணங்கள்",
    profile: "சுயவிவரம்",
    download: "பதிவிறக்கம்",
    aiTranslate: "ஏஐ மொழிபெயர்ப்பு",
    doctorName: "மருத்துவர் பெயர்",
    diagnosis: "நோய் கண்டறிதல்",
    prescription: "மருந்து",
    notes: "குறிப்புகள்",
    visitDate: "வருகை தேதி",
    nextAppointment: "அடுத்த சந்திப்பு",
    suggestedTests: "பரிந்துரைக்கப்பட்ட சோதனைகள்",
    testByWorker: "தொழிலாளர் சோதனை",
    registeredWorkers: "பதிவு செய்யப்பட்ட தொழிலாளர்கள்",
    totalRecords: "மொத்த பதிவுகள்",
    healthTracking: "சுகாதார கண்காணிப்பு",
    platformBenefits: "தளத்தின் நன்மைகள்",
    uniqueHealthId: "உங்கள் அடையாளத்தின் அடிப்படையில் தனித்துவமான டிஜிட்டல் சுகாதார ஐடி",
    centralizedRecords: "ஏஐ மொழிபெயர்ப்புடன் மையப்படுத்தப்பட்ட மருத்துவ பதிவுகள்",
    easyMobileAccess: "ஓடிபி உள்நுழைவுடன் எளிதான மொபைல் அணுகல்",
    appointmentTracking: "சந்திப்பு கண்காணிப்பு மற்றும் சுகாதார நுண்ணறிவு",
    enterHealthId: "உங்கள் சுகாதார ஐடியை உள்ளிடவும்",
    enterMobile: "உங்கள் மொபைல் எண்ணை உள்ளிடவும்",
    sendOtp: "ஓடிபி அனுப்பவும்",
    verifyOtp: "ஓடிபி சரிபார்க்கவும்",
    back: "திரும்பு",
    backToHome: "முகப்புக்கு திரும்பு",
    loading: "ஏற்றுகிறது...",
    searching: "தேடுகிறது...",
    noRecordsFound: "பதிவுகள் எதுவும் கிடைக்கவில்லை",
    noAppointmentsFound: "சந்திப்புகள் எதுவும் கிடைக்கவில்லை",
    scheduled: "திட்டமிடப்பட்டது",
    completed: "நிறைவேற்றப்பட்டது",
    cancelled: "ரத்து செய்யப்பட்டது",
    rescheduled: "மறுதிட்டமிடப்பட்டது",
    purpose: "நோக்கம்",
    status: "நிலை",
    refreshData: "தரவை புதுப்பிக்கவும்"
  },
  // Adding more translations for other languages...
  te: {
    welcome: "స్వాస్థ్య ఐడికి స్వాగతం",
    workerPortal: "కార్మిక పోర్టల్",
    hospitalPortal: "ఆసుపత్రి పోర్టల్",
    governmentPortal: "ప్రభుత్వ పోర్టల్",
    accessRecords: "మీ రికార్డులను చూడండి",
    registerNow: "ఇప్పుడు నమోదు చేయండి",
    login: "లాగిన్",
    logout: "లాగౌట్",
    home: "హోమ్",
    healthId: "ఆరోగ్య ఐడి",
    mobileOtp: "మొబైల్ ఒటిపి",
    register: "నమోదు",
    name: "పేరు",
    mobileNumber: "మొబైల్ నంబర్",
    email: "ఇమెయిల్",
    address: "చిరునామా",
    dateOfBirth: "పుట్టిన తేదీ",
    aadharNumber: "ఆధార్ నంబర్",
    medicalRecords: "వైద్య రికార్డులు",
    appointments: "అపాయింట్మెంట్లు",
    documents: "డాక్యుమెంట్లు",
    profile: "ప్రొఫైల్",
    download: "డౌన్లోడ్",
    aiTranslate: "AI అనువాదం",
    doctorName: "వైద్యుడి పేరు",
    diagnosis: "నిర్ధారణ",
    prescription: "మందు",
    notes: "గమనికలు",
    visitDate: "సందర్శన తేదీ",
    nextAppointment: "తదుపరి అపాయింట్మెంట్",
    suggestedTests: "సూచించిన పరీక్షలు",
    testByWorker: "కార్మికుడి పరీక్ష",
    registeredWorkers: "నమోదైన కార్మికులు",
    totalRecords: "మొత్తం రికార్డులు",
    healthTracking: "ఆరోగ్య ట్రాకింగ్",
    platformBenefits: "ప్లాట్ఫారమ్ ప్రయోజనాలు",
    uniqueHealthId: "మీ గుర్తింపు ఆధారంగా ప్రత్యేక డిజిటల్ ఆరోగ్య ఐడి",
    centralizedRecords: "AI అనువాదంతో కేంద్రీకృత వైద్య రికార్డులు",
    easyMobileAccess: "OTP లాగిన్తో సులభమైన మొబైల్ యాక్సెస్",
    appointmentTracking: "అపాయింట్మెంట్ ట్రాకింగ్ మరియు ఆరోగ్య అంతర్దృష్టులు",
    enterHealthId: "మీ ఆరోగ్య ఐడిని నమోదు చేయండి",
    enterMobile: "మీ మొబైల్ నంబరును నమోదు చేయండి",
    sendOtp: "OTP పంపండి",
    verifyOtp: "OTP ధృవీకరించండి",
    back: "వెనుకకు",
    backToHome: "హోమ్‌కు వెనుకకు",
    loading: "లోడ్ అవుతోంది...",
    searching: "వెతుకుతోంది...",
    noRecordsFound: "రికార్డులు కనుగొనబడలేదు",
    noAppointmentsFound: "అపాయింట్మెంట్లు కనుగొనబడలేదు",
    scheduled: "షెడ్యూల్ చేయబడింది",
    completed: "పూర్తయింది",
    cancelled: "రద్దు చేయబడింది",
    rescheduled: "మళ్లీ షెడ్యూల్ చేయబడింది",
    purpose: "ప్రయోజనం",
    status: "స్థితి",
    refreshData: "డేటాను రిఫ్రెష్ చేయండి"
  }
  // Add remaining languages (kn, gu, mr, bn, pa, or, as) with similar structure...
};

export const useTranslation = (language: string) => {
  const t = (key: string): string => {
    const langTranslations = translations[language as keyof typeof translations] || translations.en;
    return langTranslations[key as keyof typeof langTranslations] || key;
  };

  return { t };
};