// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ftsalpwfnhrzjrrgbxus.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ0c2FscHdmbmhyempycmdieHVzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzMDMzOTksImV4cCI6MjA3Mzg3OTM5OX0.W6-CmCn5wQr8r0T0AdOK0clcjBMWNrXRQu1RvXEAktI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});